### ISSUE TITLE
 about AAAI 2023 code release timeline

### ISSUE THREAD

**Issue by bc-li** [qqqyd/MOSTEL#2]
Hi Yadong,

I hope this message finds you well. I recently came across the paper you submitted to the AAAI 2023 conference and was impressed by the work! I noticed in the repository's README file that you have included a to-do list. I was wondering if you have any updates on the progress of the code and if you have an estimated timeline for its release?

Thank you for your time and for sharing your research with the community.

Best regards,
Bocheng

**Comment by qqqyd** [comment]
Thank you for your interest in our work. We are currently cleaning the code and evaluation dataset. We plan to release them before March 1st.

**Comment by bc-li** [comment]
> Thank you for your interest in our work. We are currently cleaning the code and evaluation dataset. We plan to release them before March 1st.

Thank you for your prompt response! Looking forward to it :)
