### ISSUE TITLE
demo_img运行结果

### ISSUE THREAD

**Issue by Question406** [qqqyd/MOSTEL#3]
您好，能把demo_img的运行结果给出来参考吗，我不太确定我运行的是否正确，我的生成结果中原图上的字没有去掉，也没有新的字生成

**Comment by qqqyd** [comment]
可以使用提供的模型在Tamper-Syn2k和Tamper-Scene上评估验证，量化指标应与论文一致。demo_img仅为训练过程中周期性验证查看模型可视化性能使用，因此在其中加入了不同难度的样本，对于困难样本的确存在篡改效果不好的情况

**Comment by Question406** [comment]
感谢回复，我尝试了用eval_scene.sh来进行Tamper-Scene上的评估，但是生成的图片都没有成功把文字改掉，OCR accuracy是0，我看了一下具体的生成结果，似乎是迁移字体后的o_mask_t效果很差，基本都是没有字形的纯黑色mask，您能想到什么可能出错的地方吗？

**Comment by qqqyd** [comment]
有可能是环境配置原因吧，目前代码在文档说明的环境下测试没问题
