### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by alloydas** [qqqyd/MOSTEL#4]
Hello its a good work. I read the paper and it motivates me to explore STE.

I have tried to run your code everything is working fine. But I can't download the dataset. It's need the college ID. My ID is not working there. 

If you release the documentation of the dataset creation it will be helpful to me. I hope you understand the issue. 

Thanks in advanced. Best of luck for your next project.

**Comment by qqqyd** [comment]
The netdisk doesn't need any ID. You can access it by entering the password(t6bq). Our synthetic data is generated by [SRNet-Datagen](https://github.com/youdao-ai/SRNet-Datagen).

**Comment by alloydas** [comment]
Thank you for your reply.

I have tried many time but I can't download it. Can you please share it via google drive or one drive link?

**Comment by qqqyd** [comment]
We have uploaded them to OneDrive. You can download [datasets](https://mailustceducn-my.sharepoint.com/:f:/g/personal/qqqyd_mail_ustc_edu_cn/ElyDQHgge-VNhpwmwXm2YmIBzNGy-1IxH_xq7mzAsWEk0A)(password: t6bq) and [models](https://mailustceducn-my.sharepoint.com/:f:/g/personal/qqqyd_mail_ustc_edu_cn/En6jxV64oUxAlEOC76Nwo0EBcdHNgZzxt5pZULX5_JGrSA)(password: 85b5).

**Comment by alloydas** [comment]
Thank you very much for this link previous link was different.

**Comment by alloydas** [comment]
I have downloaded the datasets and checked. In the dataset folders i_t was not there. Can you upload i_t folders please?

**Comment by qqqyd** [comment]
i_t is generated during the running of the code. Please refer to [standard_text.py](https://github.com/qqqyd/MOSTEL/blob/main/standard_text.py)
