### ISSUE TITLE
Why is the inference output a background image instead of a fused composite image

### ISSUE THREAD

**Issue by 136LYJ** [qqqyd/MOSTEL#7]
![image](https://github.com/qqqyd/MOSTEL/assets/50669398/0b77523e-33c9-4d3a-9146-6c833b9b1d4c)

**Comment by 136LYJ** [comment]
我猜是不是预训练模型没有放效果最好的那个

**Comment by qqqyd** [comment]
提供的模型在Tamper-Syn2k和Tamper-Scene上评估验证的结果与论文一致，请检查环境配置是否有问题

**Comment by 136LYJ** [comment]
tps之后的图像应该是有问题的，但是找不到原因
mask贴合原字形时感觉背景效果反而更差了
![image](https://github.com/qqqyd/MOSTEL/assets/50669398/7a4b1b54-3d9e-4e97-803a-f0c945bee21b)

**Comment by 136LYJ** [comment]
确实是pytorch版本问题，需要在https://pytorch.org/get-started/previous-versions/ 官网找到对应cuda版本的1.7.1的pytorch
![image](https://github.com/qqqyd/MOSTEL/assets/50669398/f190a70c-6125-4767-bc5c-66a3439089ec)

**Comment by fenghe12** [comment]
您好 请问您是怎么解决的这个问题 我在4090上跑预训练的模型遇到了和您类似的结果。（推理出的图片上貌似没有文字，只有背景）

**Comment by 136LYJ** [comment]
> 您好 请问您是怎么解决的这个问题 我在4090上跑预训练的模型遇到了和您类似的结果。（推理出的图片上貌似没有文字，只有背景）

pytorch版本问题

**Comment by fenghe12** [comment]
您好，请问您用的什么显卡，能提供一下安装的依赖的版本和命令吗，我尝试了很久都无法正确推理（我使用4090，cuda11.8）

**Comment by fenghe12** [comment]
您好 方便留个联系方式吗
