### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by yang-chenyu104** [qqqyd/MOSTEL#8]
训练的时候出现[1,64,256]这个shape数据，看代码是mask形成，改成torch.ones([3] + self.cfg.data_shape)后续出现shape不匹配请问这个问题怎么解决

**Comment by qqqyd** [comment]
报错是在哪里出现的？我们提供的代码是能够正常运行的，请检查代码是否有修改

**Comment by yang-chenyu104** [comment]
谢谢大佬，我在检查一下，可能是路径方面



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月29日(周五) 晚上8:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qqqyd/MOSTEL] 训练问题 (Issue #8)




 
报错是在哪里出现的？我们提供的代码是能够正常运行的，请检查代码是否有修改

**Comment by yang-chenyu104** [comment]
感谢感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月30日(周六) 上午9:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qqqyd/MOSTEL] 训练问题 (Issue #8)




 
Closed #8 as completed.
